version: "3.5"

services:
  vm-charts-api-local:
    image: node:latest
    working_dir: /app
    command: npm run docker
    container_name: vm-charts-api
    ports:
      - 3001:3001
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - MONGO_HOST=db
      - JWT_SECRET='csdfsdfsflsknfskdf464_335hnsjdhfsjf'
      - VIRTUAL_HOST=api.vm-charts.local.com
    networks:
      - vm-charts-network
    depends_on:
      - redis
      - db
      - nginx-proxy-api

  vm-charts-api-prod:
    build: .
    container_name: vm-charts-api
    ports:
      - 3001:3001
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - MONGO_HOST=db
      - JWT_SECRET='csdfsdfsflsknfskdf464_335hnsjdhfsjf'
    networks:
      - vm-charts-network
    depends_on:
      - redis
      - db

  redis:
    image: redis:6.2.4
    container_name: vm-charts-redis
    volumes:
      - redis-data:/data/
    networks:
      - vm-charts-network

  nginx-proxy-api:
    image: jwilder/nginx-proxy
    ports:
      - 81:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - vm-charts-network

  db:
    image: mongo
    container_name: vm-charts-db
    volumes:
      - mongo-data:/data/db
    networks:
      - vm-charts-network


networks:
  vm-charts-network:
    name: vm-charts-network

volumes:
  redis-data:
  mongo-data: